# Assumes csv generated by provided mmwave parser
# Run from console -> first argument is the file to read, the second will be the prefix of the file for each trial
# For example, the second argument being kick will produce kick0.csv, kick1.csv...
# 3rd argument is mode cfg mode (vel vs pos)
# Assumes 30 fps for DAQ and 2 seconds per trial -> 60 frames per trial

import os
import sys
from colorama import init as colorama_init
from colorama import Fore

colorama_init()

# fileName = "data (csv)/optVelRes/kickForward/kickForward.csv"
# fileName = "data (csv)/optVelRes/sidewaysWalking/sidewaysWalking.csv"
# fileName = "data (csv)/optVelRes/kickSideways/kickSideways.csv"
# fileName = "data (csv)/optVelRes/forwardWalking/forwardWalking.csv"
fileName = "data (csv)/optVelRes/none/none.csv"



# fileName = "data (csv)/optVelRes/none/noGesture.csv"

try:
    newFileLocation = sys.argv[2]
    if newFileLocation == "pos":
        newFileLocation = "data (csv)/optPosRes/"
    else:
        newFileLocation = "data (csv)/optVelRes/"
except:
    print(Fore.YELLOW + "Assuming default mode (optimized velocity cfg)" + Fore.RESET)
    newFileLocation = "data (csv)/optVelRes/"

newFilePrefix = sys.argv[1]
if newFilePrefix not in os.listdir(newFileLocation):
    os.makedirs(newFileLocation + newFilePrefix)
newFileLocation = newFileLocation + newFilePrefix + "/"

file = open(fileName)
listOfLines = file.readlines()
file.close()

TrialIdx=0
for i in range(len(listOfLines)):
    line_i = listOfLines[i].split(',')
    if(line_i[0] == '0' and (line_i[1] == '0' or line_i[1] == "None")):
        TrialIdx = TrialIdx + 1
        try:
            try:
                newFile.close()
            except:
                pass
            newFile = open(newFileLocation + newFilePrefix + str(TrialIdx) + '.csv', 'x')
        except:
            raise Exception(Fore.RED + "That gesture data already exists in this location. Please delete it or change it's location")
    newFile.write(listOfLines[i])

